name: rtl_433_discovery
version: "2024.3.1"
description: Receive wireless sensor data via an SDR dongle and rtl_433
slug: rtl_433
url: https://github.com/catduckgnaf/rtl_433_haos_addon
init: false 
arch:
- armv7
- aarch64
- amd64
- i386
- armhf
map:
- config:rw
- share:rw
services:
- mqtt:want
usb: true
udev: true
options:
  discovery_retain: true
  discovery_force_update: true
  discovery_host: "core-mosquitto"
  discovery_port: 1883
  discovery_user: ""
  discovery_password: ""
  discovery_topic: "rtl_433/+/events"
  discovery_prefix: "homeassistant"
  device_topic_suffix: ""
  discovery_interval: 600
  discovery_ids: 23 69
  discovery_log_level: "default"
  other_args: ""

schema:
  discovery: bool?
  discovery_ids: "str?"
  discovery_log_level: "list(default|quiet|debug)"
  discovery_retain: bool?
  discovery_force_update: bool?